/*
 * Editor client script for DB table firms
 * Automatically generated by http://editor.datatables.net/generator
 */

(function($){

$(document).ready(function() {
	var editor = new $.fn.dataTable.Editor( {
		"ajax": "php/table.firms.php",
		"table": "#firms",
		"fields": [
			{
				"label": "Name",
				"name": "Name",
				"type": "text"
			},
			{
				"label": "Description",
				"name": "Description",
				"type": "textarea"
			},
			{
				"label": "Contact Person",
				"name": "ContactPerson",
				"type": "text"
			},
			{
				"label": "Date",
				"name": "Date",
				"type": "date",
				"dateFormat": "dd\/mm\/y",
				"dateImage": "images\/calender.png"
			},
			{
				"label": "Address",
				"name": "Address",
				"type": "textarea"
			},
			{
				"label": "City",
				"name": "City",
                                "type": "select",
				"ipOpts": [
					
                                        {
						"label": " Adana ",
						"value": " Adana "
					},
					{
						"label": " Adıyamanyaman ",
						"value": " Adıyaman "
					},
					{
						"label": " Afyonkarahisar ",
						"value": " Afyonkarahisar "
					},
					{
						"label": " Ağrı ",
						"value": " Ağrı "
					},
					{
						"label": " Aksaray ",
						"value": " Aksaray "
					},
					{
						"label": " Amasya ",
						"value": " Amasya "
					},
					{
						"label": " Ankara ",
						"value": " Ankara "
					},
					{
						"label": " Antalya ",
						"value": " Antalya "
					},
					{
						"label": " Ardahan ",
						"value": " Ardahan "
					},
					{
						"label": " Artvin ",
						"value": " Artvin "
					},
					{
						"label": " Aydınn ",
						"value": " Aydınn "
					},
					{
						"label": " Balıkesir ",
						"value": " Balıkesir "
					},
					{
						"label": " Bartın ",
						"value": " Bartın "
					},
					{
						"label": " Batman ",
						"value": " Batman "
					},
					{
						"label": " Bayburt ",
						"value": " Bayburt "
					},
					{
						"label": " Bilecik ",
						"value": " Bilecik "
					},
					{
						"label": " Bingöl ",
						"value": " Bingöl "
					},
					{
						"label": " Bitlis ",
						"value": " Bitlis "
					},
					{
						"label": " Bolu ",
						"value": " Bolu "
					},
					{
						"label": " Burdur ",
						"value": " Burdur "
					},
					{
						"label": " Bursa ",
						"value": " Bursa "
					},
					{
						"label": " Çanakkale ",
						"value": " Çanakkale "
					},
					{
						"label": " Çankırı ",
						"value": " Çankırı "
					},
					{
						"label": " Çorum ",
						"value": " Çorum "
					},
					{
						"label": " Denizli ",
						"value": " Denizli "
					},
					{
						"label": " Diyarbakır ",
						"value": " Diyarbakır "
					},
					{
						"label": " Düzce ",
						"value": " Düzce "
					},
					{
						"label": " Edirne ",
						"value": " Edirne "
					},
					{
						"label": " Elazığ ",
						"value": " Elazığ "
					},
					{
						"label": " Erzincan ",
						"value": " Erzincan "
					},
					{
						"label": " Erzurum ",
						"value": " Erzurum "
					},
					{
						"label": " Eskişehir ",
						"value": " Eskişehir "
					},
					{
						"label": " Gaziantep ",
						"value": " Gaziantep "
					},
					{
						"label": " Giresun ",
						"value": " Giresun "
					},
					{
						"label": " Gümüşhane ",
						"value": " Gümüşhane "
					},
					{
						"label": " Hakkari ",
						"value": " Hakkari "
					},
					{
						"label": " Hatay ",
						"value": " Hatay "
					},
					{
						"label": " Iğdır ",
						"value": " Iğdır "
					},
					{
						"label": " Isparta ",
						"value": " Isparta "
					},
					{
						"label": " İstanbul ",
						"value": " İstanbul "
					},
					{
						"label": " İzmir ",
						"value": " İzmir "
					},
					{
						"label": " Karaman ",
						"value": " Karaman "
					},
					{
						"label": " Karabük ",
						"value": " Karabük "
					},
					{
						"label": " Kars ",
						"value": " Kars "
					},
					{
						"label": " Kastamonu ",
						"value": " Kastamonu "
					},
					{
						"label": " Kayseri ",
						"value": " Kayseri "
					},
					{
						"label": " Kırıkkale ",
						"value": " Kırıkkale "
					},
					{
						"label": " Kırklareli ",
						"value": " Kırklareli "
					},
					{
						"label": " Kırşehir ",
						"value": " Kırşehir "
					},
					{
						"label": " Kilis ",
						"value": " Kilis "
					},
					{
						"label": " Kocaeli ",
						"value": " Kocaeli "
					},
					{
						"label": " Konya ",
						"value": " Konya "
					},
					{
						"label": " Kütahya ",
						"value": " Kütahya "
					},
					{
						"label": " Malatya ",
						"value": " Malatya "
					},
					{
						"label": " Manisa ",
						"value": " Manisa "
					},
					{
						"label": " Kahramanmaraş ",
						"value": " Kahramanmaraş "
					},
					{
						"label": " Mardin ",
						"value": " Mardin "
					},
					{
						"label": " Mersin ",
						"value": " Mersin "
					},
					{
						"label": " Muğla ",
						"value": " Muğla "
					},
					{
						"label": " Muş ",
						"value": " Muş "
					},
					{
						"label": " Nevşehir ",
						"value": " Nevşehir "
					},
					{
						"label": " Niğde ",
						"value": " Niğde "
					},
					{
						"label": " Ordu ",
						"value": " Ordu "
					},
					{
						"label": " Osmaniye ",
						"value": " Osmaniye "
					},
					{
						"label": " Rize ",
						"value": " Rize "
					},
					{
						"label": " Sakarya ",
						"value": " Sakarya "
					},
					{
						"label": " Samsun ",
						"value": " Samsun "
					},
					{
						"label": " Siirt ",
						"value": " Siirt "
					},
					{
						"label": " Sinop ",
						"value": " Sinop "
					},
					{
						"label": " Sivas ",
						"value": " Sivas "
					},
					{
						"label": " Tekirdağ ",
						"value": " Tekirdağ "
					},
					{
						"label": " Tokat ",
						"value": " Tokat "
					},
					{
						"label": " Trabzon ",
						"value": " Trabzon "
					},
					{
						"label": " Tunceli ",
						"value": " Tunceli "
					},
					{
						"label": " Şanlıurfa ",
						"value": " Şanlıurfa "
					},
					{
						"label": " Şırnak ",
						"value": " Şırnak "
					},
					{
						"label": " Uşak ",
						"value": " Uşak "
					},
					{
						"label": " Van ",
						"value": " Van "
					},
					{
						"label": " Yalova ",
						"value": " Yalova "
					},
					{
						"label": " Yozgat ",
						"value": " Yozgat "
					},
					{
						"label": " Zonguldak ",
						"value": " Zonguldak "
					},
					{
						"label": " Other",
						"value": " Other"
					}
				]
			},
			{
				"label": "Type",
				"name": "Type",
				"type": "select",
				"ipOpts": [
					
                                        {
						"label": "Computer Software ",
						"value": "Computer Software "
					},
					{
						"label": " Computer Hardware ",
						"value": " Computer Hardware "
					},
					{
						"label": " IT ",
						"value": " IT "
					},
					{
						"label": " Telecommunication ",
						"value": " Telecommunication "
					},
					{
						"label": " Game ",
						"value": " Game "
					},
					{
						"label": " Electronics ",
						"value": " Electronics "
					},
					{
						"label": " Research and Development ",
						"value": " Research and Development "
					},
					{
						"label": " Education ",
						"value": " Education "
					},
					{
						"label": " Marketing ",
						"value": " Marketing "
					},
					{
						"label": " Government ",
						"value": " Government "
					},
					{
						"label": " Media ",
						"value": " Media "
					},
					{
						"label": " Public Company ",
						"value": " Public Company "
					},
					{
						"label": " Commercial Company ",
						"value": " Commercial Company "
					},
					{
						"label": " Financial Services ",
						"value": " Financial Services "
					},
					{
						"label": " Business Services ",
						"value": " Business Services "
					},
					{
						"label": " Health Care ",
						"value": " Health Care "
					},
					{
						"label": " Insurance ",
						"value": " Insurance "
					},
					{
						"label": " Entertainment ",
						"value": " Entertainment "
					},
					{
						"label": " Product Manufacturing ",
						"value": " Product Manufacturing "
					},
					{
						"label": " Food Manufacturing ",
						"value": " Food Manufacturing "
					},
					{
						"label": " Machinery Manufacturing ",
						"value": " Machinery Manufacturing "
					},
					{
						"label": " Oil & Gas Field Services ",
						"value": " Oil & Gas Field Services "
					},
					{
						"label": " Real Estate ",
						"value": " Real Estate "
					},
					{
						"label": " Transportation ",
						"value": " Transportation "
					},
					{
						"label": " Enviromental ",
						"value": " Enviromental "
					},
					{
						"label": " Other",
						"value": " Other"
					}
				]
                        },
			{
				"label": "Sponsor",
				"name": "Sponsor",
				"type": "select",
				"ipOpts": [
					{
						"label": "Yes",
						"value": "Yes"
					},
					{
						"label": "No",
						"value": "No"
					}
				]
			}
		]
	} );

	$('#firms').dataTable( {
		"dom": "Tfrtip",
		"ajax": "php/table.firms.php",
		"columns": [
			{
				"data": "FirmID"
			},
			{
				"data": "Name"
			},
			{
				"data": "Description"
			},
			{
				"data": "ContactPerson"
			},
			{
				"data": "Date"
			},
			{
				"data": "Address"
			},
			{
				"data": "City"
			},
			{
				"data": "Type"
			},
			{
				"data": "Sponsor"
			}
		],
		"tableTools": {
			"sRowSelect": "os",
			"aButtons": [
				{ "sExtends": "editor_create", "editor": editor },
				{ "sExtends": "editor_edit",   "editor": editor },
				{ "sExtends": "editor_remove", "editor": editor }
			]
		}
	} );
} );

}(jQuery));

